Thermal policy
Junchao-Mellanox/sonic-platform-daemons pull request #3
Opened 2019-12-18 10:38 UTC by Junchao-Mellanox

What I did?
1. Add FanUpdater to get fan information and write it to database
2. Add TemperUpdater to get temperature information and write it to database
3. Add ThermalControlDaemon to run the thermal policy 

How to verify?
1. show platform fanstatus
2. show platform temperature
3. View syslog make sure thermalctld is up and there is no error logs

2019-12-23 08:45 UTC, Junchao-Mellanox commented on sonic-thermalctld/scripts/thermalctld
> +    #from swsscommon import swsscommon
Remove this line.

2019-12-23 08:51 UTC, Junchao-Mellanox commented on sonic-thermalctld/scripts/thermalctld
> +    def destroy(self):
deinit

2019-12-23 08:59 UTC, Junchao-Mellanox commented on sonic-thermalctld/scripts/thermalctld
> +        self.over_temper = False
temper ->temperature

2019-12-23 09:54 UTC, Junchao-Mellanox commented on sonic-thermalctld/scripts/thermalctld
> +    def destroy(self):
deinit

2019-12-23 10:01 UTC, Junchao-Mellanox commented on sonic-thermalctld/scripts/thermalctld
> +    # Interval to run thermal control logical
logical->logic

2019-12-23 10:03 UTC, Junchao-Mellanox commented on sonic-thermalctld/scripts/thermalctld
> +        import sonic_platform.platform
try move it to top

2019-12-24 02:20 UTC, keboliu commented on sonic-thermalctld/scripts/thermalctld
> +        if sig == signal.SIGHUP:
please test and make sure thread will also exit on SIGTERM

2019-12-24 02:31 UTC, keboliu commented on sonic-thermalctld/scripts/thermalctld
> +                logger.log_warning('Fan speed or target_speed or tolerance become unavailable.')
make log more specific to indicate which speed is not available.

2019-12-24 02:41 UTC, keboliu commented on sonic-thermalctld/scripts/thermalctld
> +        status = (target_speed - speed > tolerance)
this is not the correct way to check over speed or under-speed, should be:    target_speed*(1-tolerance) < speed < target_speed*(1+tolerance)

2019-12-24 02:41 UTC, keboliu commented on sonic-thermalctld/scripts/thermalctld
> +        status = (speed - target_speed > tolerance)
as above comments

2019-12-24 02:52 UTC, keboliu requested changes
as comments

2020-02-01 02:50 UTC, closed without merging